spring:
  application:
    name: frontend-edge-service

server:
  port: 18100

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:18300/eureka}
  instance:
    preferIpAddress: true

management:
  server:
    port: 28100
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    greetings:
      path: /greeting
      serviceId: application-service
      stripPrefix: true
