spring:
  application:
    name: appl-edge-service

server:
  port: 18200

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:18300/eureka}
  instance:
    preferIpAddress: true

management:
  server:
    port: 28200
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

zuul:
  ignoredServices: '*'
  routes:
    countries:
      path: /soap/*
      serviceId: soap-service
      stripPrefix: false
      