spring:
  application:
    name: application-service

server:
  #port: ${random.int(18110,18119)}
  port: 18110

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:18300/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  server:
    # port: ${random.int(28110,28119)}
    port: 28110
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

