server:
  port: 18300

spring:
  application:
    name: registry-service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:18300/eureka}
  server:
    peer-node-read-timeout-ms: 10000

management:
  server:
    port: 28300
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
