spring:
  application:
    name: soap-service

server:
  port: ${PORT:0}
  # port: 18210

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:18300/eureka}
  instance:
    preferIpAddress: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  server:
    port: ${PORT:0}
    # port: 28210
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

