server:
  port: 18400
  address: 0.0.0.0

spring:
  application:
    name: admin-service

  boot:
    admin:
      client:
        url: http://localhost:18400
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:18300/eureka}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true