server:
  port: 18200
  address: 0.0.0.0

spring:
  application:
    name: admin-service

#  security:
#    user:
#      name: admin
#      password: admin

  boot:
    admin:
      client:
        url: http://localhost:18200
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}

healthaggregator:
  neededServices:
    - APPLICATION-SERVICE
    - FRONTEND-EDGE-SERVICE
    - APPL-EDGE-SERVICE
    - REGISTRY-SERVICE

#      notify:
#        mail:
#          to:
#  mail:
#    host:
#    username:
#    password:
#    port:
#    properties:
#      mail:
#        smtp:
#          auth:
#          starttls.enable:

#configs to give secured server info
management:
  endpoints:
    web:
      exposure:
        include: "*""
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:18100/eureka}
  instance:
    preferIpAddress: true